# Generated by Django 5.1.5 on 2025-01-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=225)),
                ('current_datetime', models.DateTimeField(auto_now_add=True)),
                ('github_url', models.URLField()),
            ],
        ),
    ]
